/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface BankCreateInput {
  /**
   * bank name
   */
  name: string;
}

export interface BankUpdateInput {
  /**
   * bank name
   */
  name?: string;
}
